### PR TITLE
Fix multiple requests at the same time

### LINKED ISSUE #7: multiple requests at the same time
when using this with openai i get an error like 

```
Error: invalid_request_error: An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_OBj7vr6sZNBBSwCE5b7KmxAl, call_3fxB5UUMeL6i6G7I3HraVfY9, call_qRqRGsLzDM3OeF64rn9FBNVB, call_QBEeDV5ObrwvpAqJedFeqMrw
```

but this only happens if i give it a prompt that requires multiple sequential calls to the MCP tools.

the mcp server I'm using works ok with the claude desktop app and it works with ollama (but ollama seems incapable of making a bunch of queries in a row).

### PR DESCRIPTION
**Pull request by corani**
Previously when multiple tool calls were requested by the LLM we got the error `An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'.` although the calls were processed.

Apparently each response needs to be its own message, rather than its own block.

Closes #7

### CODE REVIEW

File: cmd/root.go [hunk 1]
```diff
@@ -451,10 +451,12 @@ func runPrompt(
 	})
 
 	if len(toolResults) > 0 {
-		*messages = append(*messages, history.HistoryMessage{
-			Role:    "user",
-			Content: toolResults,
-		})
+		for _, toolResult := range toolResults {
+			*messages = append(*messages, history.HistoryMessage{
+				Role:    "tool",
```
Comment (corani) [inline cmd/root.go:456]: I'm not certain about the role, but this works for me...
